version: "3.5"

# volumes:
#   redis_data:

networks:
  outside:
    name: host
    external: true

services:
  react_demo:
    image: react_demo
    networks:
      - outside
    volumes: 
      - .:/app/ # copy entire app into container
  